### ISSUE TITLE
Extending support for rate limit headers

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/chaos-client#119]
## Description
Follow up of https://github.com/projectdiscovery/chaos-client/issues/111. The client should interpret the `Retry-After` header. If present (429 status code) the client should wait for the specified amount of time (in seconds) before issuing a new request.

```
...
Retry-After: 60
...
```

**Comment by tarunKoyalwar** [comment]
Depends on https://github.com/projectdiscovery/chaos-cache/issues/152

**Comment by ehsandeep** [comment]
Suppressed by new API.
