### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by fabaff** [projectdiscovery/chaos-client#12]
Could you please add a LICENSE file and publish a new release? Thanks.

At the moment it's not clear what kind of licence is used for the source. It's a requirement for packaging the client.

**Comment by ehrishirajsharma** [comment]
Thanks @fabaff. Just added the [license file](https://github.com/projectdiscovery/chaos-client/blob/master/LICENSE), please check.

**Comment by fabaff** [comment]
@ehrishirajsharma, thank you, for your quick reaction.
