### ISSUE TITLE
Could not get subdomains: invalid status code received: 401

### ISSUE THREAD

**Issue by Droidzzzio** [projectdiscovery/chaos-client#16]
I received my beta API key yesterday , and while testing it i am not able to fetch the subdomains

chaos.exe -d tesla.com -key somekey -silent

Response
[←[1;31mFTL←[0m] Could not get subdomains: invalid status code received: 401

**Comment by Droidzzzio** [comment]
![chaos_error](https://user-images.githubusercontent.com/34626959/84560554-e8a8d380-ad62-11ea-9f00-3ed0ed58321c.PNG)

**Comment by bauthard** [comment]
Hey @Droidzzzio, 

Can you try with `chaos -d uber.com -silent -key KEY_HERE`

**Comment by Droidzzzio** [comment]
Tested and still not working
![chaos-still-not-working](https://user-images.githubusercontent.com/34626959/84561770-dc297880-ad6c-11ea-96ec-d81da00a846d.PNG)

**Comment by Droidzzzio** [comment]
When i got the API key in the mail , there was something written in brackets that the API key will be usable in next 30 min , so may be the key is not usable still. I am just throwing a guess.

**Comment by bauthard** [comment]
Should be fixed now @Droidzzzio.

**Comment by Droidzzzio** [comment]
thank You , the issue is fixed now
