### ISSUE TITLE
Inconsistent result by the chaos client 

### ISSUE THREAD

**Issue by serialfuzzer** [projectdiscovery/chaos-client#189]
### Current Behavior:
I scanned subdomains of the same scope 2 times using the command:
`cat scope | chaos -silent > 1.txt`
`cat scope | chaos -silent > 2.txt`

However, when I compare number of lines in both the files, you can see the result in the screenshot:

![image](https://github.com/projectdiscovery/chaos-client/assets/22111782/9a818beb-a070-4e36-95e8-e8a73ffafe1b)

### Expected Behavior:
The expected behavior is that both the files should have equal number of lines or subdomains.

**Comment by serialfuzzer** [comment]
In my case, it's a recent issue. I have integrated Chaos within my own tool and I observed inconsistencies so I went to investigate it and discovered this. This happens when the number of subdomains is huge. Doesn't happen in small scope.

**Comment by najuser** [comment]
"When I run chaos client over a long period of time, I am also getting the same issue"

**Comment by serialfuzzer** [comment]
Closing this issue as it's solved for me, and I haven't been able to reproduce this behavior for a long time.
