### ISSUE TITLE
Chaos not working properly due to some SSL certificate problem please check it

### ISSUE THREAD

**Issue by sanjai-AK47** [projectdiscovery/chaos-client#204]
### Steps To Reproduce:
```bash
chaos -d google.com
```

**Comment by MetzinAround** [comment]
Hi @sanjai-AK47 !

unless you've changed it, the command for chaos is actually `chaos client`. I was unable to reproduce your error. 


![Screenshot -0926 at 19 56](https://github.com/projectdiscovery/chaos-client/assets/65838556/161cb647-893f-427e-99fa-69afde8c066d)

**Comment by ehsandeep** [comment]
This is fixed already.

**Comment by sanjai-AK47** [comment]
@MetzinAround Sorry that I forgot that but after sometime the ssl issue was cleared and Also know what are the changes has applied after resolved that problem
