### ISSUE TITLE
Rate limit on apikey usage? flag to provide list of domains

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/chaos-client#30]
Hello!

First of all, just amazing thing you guys built here. 

The question is, if I want to run chaos over a big number of domains, how will the rate-limit be? Lets say i want to get all subdomains of the h1 wildcards, would i get rate-limit in the middle?

As a side request, wouldn't it be possible to add a flag like -list or -file to just provide chaos with a list of domains instead of using -d to provide a single domain? So all subdomains can be requests in one go.

Thanks in advance <3

**Comment by marcelo321** [comment]
Ok so I read all policy and found this:

> The API is rate-limited to 1 request at time per token (you can issue the next request only when the previous one is finished).

Then if i make a while loop to go one by one, there shouldn't be any problem even if there are more than 100 domains right? Just want to make sure. 

I'm impressed by this tool. more results than any other tool out there <3

**Comment by bauthard** [comment]
Hi @marcelo321, 

Rate limit applies as it's listed no matter how you request them, and if you see the readme, there is already a flag to support list input with `dL` flag. 

Thank you for the feedback, let me know if you any more questions.

**Comment by bauthard** [comment]
Closing as this has been answered.
