### ISSUE TITLE
[Feature] Client side filterning for subdomain search

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/chaos-client#38]
Right now we aren't allowed to search for subdomains like `*.abc.domain.com`, only first level domains.

Wouldn't be possible to add a feature to get all domains of `domain.com` and filter them to retrieve only the ones we are requesting? Like abc.domain.com subdomains in this example.

please!

**Comment by bauthard** [comment]
@marcelo321 this is possible by adding client-side filtering on the result, for the time being, you can achieve the same with `chaos -d domain.com | grep abc.domain.com`

**Comment by marcelo321** [comment]
true! I guess I can also do it with a list of hosts by doing grep -f hosts

**Comment by sickwiz** [comment]
I would like to work on this issue. Can you please assign it to me and help me getting started.

**Comment by ehsandeep** [comment]
This will be worked on after [chaos v1 client](https://github.com/projectdiscovery/chaos-client/issues/60) will be published.

**Comment by jimen0** [comment]
Hi @ehsandeep - Would it be possible to get beta access to chaos v1 client to provide some feedback before a release is tagged? Thanks! Also, please add my 👍🏻 to this feature request.
