### ISSUE TITLE
Adding "stdin" support to upload data to chaos dataset

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/chaos-client#4]
As of now, chaos client does support file input upload. 

```
chaos -f subdomains.txt
```

to make it more usable with the flow, I wanted to run other tools like `subfinder` and upload the output on the go, so next time I can just query those data from `chaos` dataset instead of running `subfinder` each time. 

```
subfinder -d ube.com | chaos update
```

**Comment by Mzack9999** [comment]
Implemented in #5
