### ISSUE TITLE
Security Error

### ISSUE THREAD

**Issue by identityxidentityx** [projectdiscovery/chaos-client#48]
Hello, I'm getting this error when installing SubFinder:

verifying github.com/projectdiscovery/chaos-client@v0.1.7: checksum mismatch
        downloaded: h1:NSC/rjZVfg1gowKBadpjtxDpMhmgnzXGQ7iDstaFvGI=
        go.sum:     h1:8M1LazT+lD3qJP1ERWXiVzQn9lPMO3p6v3qsiGNKUlQ=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

What could be happening? Only happens with this tool.

**Comment by ehsandeep** [comment]
This is fixed already with the latest release of subfinder, closing now.
