### ISSUE TITLE
Search by word

### ISSUE THREAD

**Issue by myuyu** [projectdiscovery/chaos-client#69]
### Please describe your feature request:
Adding search using only word for  subdomains in chaos it would be really awesome

### Describe the use case of this feature:
there's such a lot of cases when you want to search through word only not with full domain for example this will be useful when you want to : 
1. Extract subdomains for a sepcific CMS or instance like search for subdomains contains `jira`
2. get external domains for specific target such : `paypal`

**Comment by ehsandeep** [comment]
@myuyu chaos client is go client to pull the results from chaos DB and can only support features offered via chaos API, and unfortunately, chaos API doesn't support search by keyword, so this request can not be supported.
